name: gha_cli
description: >
  CLI tool for generating GitHub Actions workflows in Dart with init templates,
  workflow generation, and type-safe workflow definitions.
version: 1.0.0
repository: https://github.com/kingwill101/gha-dart
topics:
  - github-actions
  - workflow
  - cli
  - ci-cd
  - automation

homepage: https://github.com/kingwill101/gha-dart

issue_tracker: https://github.com/kingwill101/gha-dart/issues
funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  gha:
  args: ^2.5.0
  path: ^1.9.0
  io: ^1.0.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  gha: gha_cli
