name: gha
description: >
  Type-safe GitHub Actions workflows in Dart with strongly typed models,
  action helpers, and YAML generation for creating workflows programmatically.
version: 0.0.2
repository: https://github.com/kingwill101/gha-dart
topics:
  - github-actions
  - workflow
  - ci-cd
  - yaml
  - automation

homepage: https://github.com/kingwill101/gha-dart

issue_tracker: https://github.com/kingwill101/gha-dart/issues
funding:
  - https://www.buymeacoffee.com/kingwill101

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  dart_mappable: ^4.3.0
  json2yaml: ^3.0.1
  path: ^1.9.0
  yaml: ^3.1.3
  json_schema: ^5.2.2

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.10
  dart_mappable_builder: ^4.3.0
  test: ^1.25.6
