import 'dart:io';

import 'package:path/path.dart' as p;

import 'workflow.dart';

/// Extension methods for [Workflow] to save workflows to files
extension WorkflowSaveExtension on Workflow {
  /// Saves the workflow to a YAML file in the specified directory.
  ///
  /// The file will be named `[name].generated.yaml` where [name] is derived
  /// from the workflow's name property (converted to lowercase with spaces
  /// replaced by hyphens), unless [filename] is provided.
  ///
  /// If [directory] is not provided, defaults to `.github/workflows`.
  /// If [filename] is provided, it will be used as-is (should include .yaml extension).
  ///
  /// Example:
  /// ```dart
  /// final workflow = Workflow(
  ///   name: 'CI',
  ///   on: WorkflowTriggers.simple(['push']),
  ///   jobs: {...},
  /// );
  ///
  /// workflow.save(); // Saves to .github/workflows/ci.generated.yaml
  /// workflow.save(directory: 'custom/dir'); // Saves to custom/dir/ci.generated.yaml
  /// workflow.save(filename: 'my-workflow.yaml'); // Saves to .github/workflows/my-workflow.yaml
  /// workflow.save(directory: 'custom', filename: 'build.yaml'); // Saves to custom/build.yaml
  /// ```
  void save({String directory = '.github/workflows', String? filename}) {
    // Ensure directory exists
    final dir = Directory(directory);
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    // Use provided filename or derive from workflow name
    final fileName = filename ?? _deriveFilename(name);
    final filePath = p.join(directory, fileName);

    // Write YAML to file with header
    final outputFile = File(filePath);
    final buffer = StringBuffer();

    // Add generated file header
    buffer.writeln('# Generated by gha - DO NOT EDIT');
    buffer.writeln('# Source: https://github.com/kingwill101/gha-dart');
    buffer.writeln();
    buffer.write(toYamlString());

    outputFile.writeAsStringSync(buffer.toString());

    print('✓ Generated: $filePath');
  }

  /// Derives a filename from the workflow name.
  ///
  /// Converts to lowercase, replaces spaces with hyphens, and removes
  /// special characters.
  String _deriveFilename(String? workflowName) {
    if (workflowName == null || workflowName.isEmpty) {
      return 'workflow.generated.yaml';
    }

    // Convert to lowercase, replace spaces with hyphens
    var filename = workflowName.toLowerCase().replaceAll(' ', '-');

    // Remove any characters that aren't alphanumeric, hyphens, or underscores
    filename = filename.replaceAll(RegExp(r'[^a-z0-9\-_]'), '');

    return '$filename.generated.yaml';
  }
}
